---
- name: AS3 deployement test
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
  - "virtual": "10.0.9.10"

  vars_files:
  - ../credentials/bigip_creds.yaml

  tasks:
  - set_fact:
      as3_body: "{{ lookup('template', './as3.j2', split_lines=False) }}"

  - name: Deploy an AS3 declaration
    uri:
      url: https://51.142.10.142:8443/mgmt/shared/appsvcs/declare/
      user: "{{username}}"
      password: "{{password}}"
      method: POST
      body: "{{ as3_body }}"
      force_basic_auth: true
      status_code: 200
      body_format: json
      validate_certs: false
    register: as3_output

  - name: AS3 OUTPUT
    debug:
      var: as3_output.json.declaration.id
...